### PR TITLE
testing

### PR DESCRIPTION
**Pull request by anthonykawa**
This change is [Reviewable](http://localhost:8080/reviews/teamblawa/testing/77)

### CODE REVIEW

**Review by anthonyk2020 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/77)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ajablanco, @anthonykawa, and @frankie95667)

___
*[.github/workflows/server.yaml, line 6 at r1](http://localhost:8080/reviews/teamblawa/testing/77#-MVJOVXM5agFP2AHH3AG:-MVJOVXM5agFP2AHH3AH:bhlmqwy) ([raw file](https://github.com/teamblawa/testing/blob/ef5d4128e8c54286f6ffcb0ee51aaa10a844b6f9/.github/workflows/server.yaml#L6)):*
> ```YAML
>   push:
>     branches:
>       - master
> ```

This is a blocking comment.

**Review by frankie95667 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/77)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ajablanco and @anthonykawa)

___
*[.github/workflows/server.yaml, line 11 at r1](http://localhost:8080/reviews/teamblawa/testing/77#-MVJOejm8JyYaSO-W5Fq:-MVJOejm8JyYaSO-W5Fr:b-mefl6v) ([raw file](https://github.com/teamblawa/testing/blob/ef5d4128e8c54286f6ffcb0ee51aaa10a844b6f9/.github/workflows/server.yaml#L11)):*
> ```YAML
> env:
>   SLACK_URL: ${{ secrets.SLACK_URL }}
>   GITTER_URL: ${{ secrets.GITTER_URL }}
> ```

non-blocking comment

**Review by anthonykawa — COMMENTED** [review]
Hello this is a messgea 

> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/77#-:-MW6_Ci31cef0Y23VXBa:b-icchs5)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ajablanco and @anthonyk2020)

___
*[.github/workflows/server.yaml, line 6 at r1](http://localhost:8080/reviews/teamblawa/testing/77#-MVJOVXM5agFP2AHH3AG:-MW6cL3DAnl_AtnO0J2n:bxqlzb9) ([raw file](https://github.com/teamblawa/testing/blob/ef5d4128e8c54286f6ffcb0ee51aaa10a844b6f9/.github/workflows/server.yaml#L6)):*
<details><summary><i>Previously, anthonyk2020 wrote…</i></summary><blockquote>

This is a blocking comment.
</blockquote></details>

:+1:  something

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/77)* status: all files reviewed, 1 unresolved discussion (waiting on @ajablanco and @anthonyk2020)

___
*[.github/workflows/server.yaml, line 6 at r1](http://localhost:8080/reviews/teamblawa/testing/77#-MVJOVXM5agFP2AHH3AG:-MXZ7GxW2Z3dkLqGDmEj:b-896fix) ([raw file](https://github.com/teamblawa/testing/blob/ef5d4128e8c54286f6ffcb0ee51aaa10a844b6f9/.github/workflows/server.yaml#L6)):*
<details><summary><i>Previously, anthonykawa (Anthony Kawa) wrote…</i></summary><blockquote>

:+1:  something 
</blockquote></details>

Done.

**Review by anthonykawa — COMMENTED** [review]
> Dismissed @anthonyk2020 from a discussion.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ajablanco)

**Pull request closed without merging**
