### PR TITLE
update

### PR DESCRIPTION
**Pull request by anthonykawa**
This change is [Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)

### CODE REVIEW

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[src/testing.ref, line 0 at r1](http://localhost:8080/reviews/teamblawa/testing/57#-MQZamhf3vYTZ_a3uA6i:-MQZamhf3vYTZ_a3uA6j:b-skm81p) ([raw file](https://github.com/teamblawa/testing/blob/44323f2ede166e2b8a483373199f927bcc1088f7/src/testing.ref#L0)):*
image

[This is a link](http://google.com)

**Review by anthonyk2020 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

___
*[src/index.js, line 7 at r2](http://localhost:8080/reviews/teamblawa/testing/57#-MQwvTNY0r9eHnhITE75:-MQwvCQS64Zy87SAekm5:bb9d37n) ([raw file](https://github.com/teamblawa/testing/blob/f4f08a22101278210bb86bdf30fb30f48c83ce80/src/index.js#L7)):*
> ```JavaScript
> 
> ReactDOM.render(
>   <React.StrictMode>
> ```

You might want to consider doing something else.

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @anthonykawa)

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: all files reviewed, 1 unresolved discussion

**Review by anthonyk2020 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: all files reviewed, 1 unresolved discussion

**Review by anthonyk2020 — APPROVED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: all files reviewed, 1 unresolved discussion

**Review by anthonyk2020 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: all files reviewed, 1 unresolved discussion

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MQyKqIb29PZndlKv64i:-MQyKqIb29PZndlKv64j:b-uacixj) ([raw file](https://github.com/teamblawa/testing/blob/f4f08a22101278210bb86bdf30fb30f48c83ce80/src/App.js#L6)):*
> ```JavaScript
>       <header className="App-header">
>         <p>
>           Edit <code>src/App.js</code> and save to reload.
> ```

This is a draft

**Review by anthonyk2020 — COMMENTED** [review]
> Dismissed @anthonykawa from a discussion.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, all discussions resolved

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MQyKqIb29PZndlKv64i:-MR2j6T9DSZGw-MB11Ph:b-nul88b) ([raw file](https://github.com/teamblawa/testing/blob/f4f08a22101278210bb86bdf30fb30f48c83ce80/src/App.js#L6)):*
<details><summary><i>Previously, anthonykawa (Anthony Kawa) wrote…</i></summary><blockquote>

This is a draft
</blockquote></details>

something

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MRMHoVC5gxL8j7us3gS:-MRMHoVC5gxL8j7us3gT:b-liha7f) ([raw file](https://github.com/teamblawa/testing/blob/302f836b5c0f1a62fcf9bafb5ca2c11ee8d509f6/src/App.js#L6)):*
> ```JavaScript
>       <header className="App-header">
>         <p>
>           Hello, there!
> ```

something new

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020 and @frankie95667)

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MRMHoVC5gxL8j7us3gS:-MRRvn-GEpsbix9z1iTb:btuacbj) ([raw file](https://github.com/teamblawa/testing/blob/302f836b5c0f1a62fcf9bafb5ca2c11ee8d509f6/src/App.js#L6)):*
<details><summary><i>Previously, anthonykawa (Anthony Kawa) wrote…</i></summary><blockquote>

something new
</blockquote></details>

-reviewer:@anthonyk2020

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020 and @anthonykawa)

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MRMHoVC5gxL8j7us3gS:-MRRw1RcEKf2mkNjRHAf:b-237inc) ([raw file](https://github.com/teamblawa/testing/blob/302f836b5c0f1a62fcf9bafb5ca2c11ee8d509f6/src/App.js#L6)):*
<details><summary><i>Previously, frankie95667 wrote…</i></summary><blockquote>

-reviewer:@anthonyk2020 
</blockquote></details>

+@anthonyk2020

**Review by frankie95667 — CHANGES_REQUESTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MRMHoVC5gxL8j7us3gS:-MRRwHDMDRakQMzHdm5i:b-n97fs6) ([raw file](https://github.com/teamblawa/testing/blob/302f836b5c0f1a62fcf9bafb5ca2c11ee8d509f6/src/App.js#L6)):*
<details><summary><i>Previously, frankie95667 wrote…</i></summary><blockquote>

+@anthonyk2020 
</blockquote></details>

-@anthonyk2020

**Review by anthonyk2020 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020, @anthonykawa, and @frankie95667)

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MRMHoVC5gxL8j7us3gS:-MRRwWR_At3cC8JlHAT-:b-237inc) ([raw file](https://github.com/teamblawa/testing/blob/302f836b5c0f1a62fcf9bafb5ca2c11ee8d509f6/src/App.js#L6)):*
<details><summary><i>Previously, frankie95667 wrote…</i></summary><blockquote>

-@anthonyk2020 
</blockquote></details>

+@anthonyk2020

**Review by anthonyk2020 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonykawa and @frankie95667)

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MRMHoVC5gxL8j7us3gS:-MRRx4Ut7mcSqVHuRUG5:b-n97fs6) ([raw file](https://github.com/teamblawa/testing/blob/302f836b5c0f1a62fcf9bafb5ca2c11ee8d509f6/src/App.js#L6)):*
<details><summary><i>Previously, anthonyk2020 wrote…</i></summary><blockquote>

+@anthonyk2020 
</blockquote></details>

-@anthonyk2020

**Review by anthonyk2020 — COMMENTED** [review]
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @anthonyk2020, @anthonykawa, and @frankie95667)

___
*[src/App.js, line 6 at r3](http://localhost:8080/reviews/teamblawa/testing/57#-MRMHoVC5gxL8j7us3gS:-MRRxBN54SSblAULovDk:b-237inc) ([raw file](https://github.com/teamblawa/testing/blob/302f836b5c0f1a62fcf9bafb5ca2c11ee8d509f6/src/App.js#L6)):*
<details><summary><i>Previously, anthonyk2020 wrote…</i></summary><blockquote>

-@anthonyk2020 
</blockquote></details>

+@anthonyk2020

**Review by anthonyk2020 — APPROVED** [review]
:lgtm:

> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57#-:-MRRyGFd7hQ7SI8LUudY:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved

**Review by anthonykawa — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](http://localhost:8080/reviews/teamblawa/testing/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anthonykawa)

**Pull request merged**
